import os,re,shutil,unicodedata,html
from PIL import Image,ImageOps
try:
    from pillow_heif import register_heif_opener;register_heif_opener()
except Exception:pass
R=os.path.dirname(os.path.abspath(__file__))+'/';U=R+'photos/';A=R+'assets/';O=R+'_site/'
os.makedirs(O+'img',exist_ok=True)
EXT=('.jpg','.jpeg','.png','.webp','.avif','.gif','.bmp','.tif','.tiff','.heic','.heif')
D={};P=[]
for f in sorted(os.listdir(U),key=str.lower):
    st,e=os.path.splitext(f)
    if e.lower() not in EXT or f.startswith('.'):continue
    try:im=ImageOps.exif_transpose(Image.open(U+f)).convert('RGB')
    except Exception as x:print('ignoré',f,x);continue
    k=re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFKD',st).encode('ascii','ignore').decode().lower()).strip('-')[:40]+'-'+str(len(P))
    t=html.escape(re.sub(r'^\d+[\s._-]+','',st).replace('_',' ').strip() or st)
    W,H=im.size;ws=sorted({w for w in(480,960,1600) if w<W}|{min(W,1600)});D[k]=(W,H,ws)
    for w in ws:im.resize((w,round(H*w/W)),Image.LANCZOS).save(f'{O}img/{k}-{w}.webp',quality=78,method=4)
    P.append((k,t))
L=Image.open(A+'logo.jpg').convert('RGB');L.resize((900,900),Image.LANCZOS).save(O+'img/logo.webp',quality=82);L.resize((1200,1200)).save(O+'img/og.jpg',quality=82)
m=L.crop((330,150,950,770));[m.resize((s,s),Image.LANCZOS).save(O+n) for s,n in((32,'favicon-32.png'),(180,'apple-touch-icon.png'),(512,'icon-512.png'))]
def pic(k,alt,eager=False,sz='(min-width:900px) 33vw,100vw'):
    W,H,ws=D[k];a=f'../img/{k}-{ws[-1]}.webp'
    return f'<img src="{a}" srcset="'+','.join(f'../img/{k}-{w}.webp {w}w' for w in ws)+f'" sizes="{sz}" width="{ws[-1]}" height="{round(H*ws[-1]/W)}" alt="{alt}" data-full="{a}"'+(' fetchpriority="high"' if eager else ' loading="lazy" decoding="async"')+'>'
SITE='https://mosaic-art.github.io/';TEL='+39 351 386 6250';WA='393513866250'
T={
'fr':dict(t="LITHOS IMPERIAL — Mosaïste d'art, mosaïque sur mesure en pierre naturelle",d="Atelier d'art mosaïste à Camporosso Mare (Ligurie) : tableaux en mosaïque, fresques, sols, piscines et reproductions de mosaïques romaines et carthaginoises, faits main en pierre naturelle.",
 tag="Créations originales et reproductions façonnées à la main en pierre naturelle, inspirées des traditions de Carthage et de Rome.",sig="L'art de la mosaïque antique sur mesure",c1="Présenter mon projet",c2="Découvrir les œuvres",
 nav=["Œuvres","Sur mesure","Reproductions","L'atelier","Contact"],
 ih="Une œuvre commence par une pierre.",ip="Chaque mosaïque est assemblée comme une œuvre d'art. La matière, la découpe, l'orientation des tesselles et les irrégularités naturelles de la pierre font son caractère. De la petite pièce de collection à la composition monumentale, l'atelier réalise créations originales et reproductions, adaptées aux dimensions et à l'univers de votre projet.",
 wh="Les œuvres",wz="Cliquer pour examiner les détails",W=[("L'arbre de vie","Médaillon"),("Khamsa","Tableau"),("Sol aux poissons","Sol"),("Pilier aux entrelacs","Œuvre murale"),("Bordure végétale","Composition en cours")],
 cats=["Tableaux et pièces de collection","Œuvres murales et fresques","Sols, médaillons et compositions","Piscines, bassins et fontaines"],
 ch="Créer ce qui n'existe encore nulle part",cp="Une idée, une image, une émotion ou simplement une matière peuvent devenir une œuvre en mosaïque. L'atelier adapte le sujet, les dimensions, les matériaux et les nuances à votre projet.",steps=["Idée","Échange","Étude artistique","Choix des matériaux","Réalisation manuelle","Œuvre terminée"],
 rh="Les chefs-d'œuvre du passé, réinterprétés par la main du mosaïste",rp="Reproductions de mosaïques historiques et d'œuvres de référence, dans le respect de leur composition et de leurs détails, à la dimension de votre choix. Inspirées des traditions mosaïstes de Carthage et de Rome. Les œuvres anciennes du domaine public peuvent être reproduites librement ; une œuvre encore protégée par le droit d'auteur nécessite l'autorisation de ses ayants droit.",
 gh="La main avant la machine",gp="Chaque tesselle participe à l'œuvre. Les variations de couleur, de texture et de veinage ne sont pas des défauts à effacer : elles font la personnalité de la matière. Taillées et posées une à une, à la main.",
 ah="Dans l'atelier",ap="Kosta Imed LITHOS, artisan mosaïste, crée des œuvres en mosaïque sur mesure à Camporosso Mare (Ligurie). Il collabore, lorsque le projet le demande, avec propriétaires, architectes, décorateurs et designers : vous imaginez l'espace, l'atelier réalise la mosaïque.",
 ph="Présenter mon projet",pp="Une idée, une image, un espace ? Décrivez-le : chaque demande est étudiée individuellement par l'atelier.",fl=["Votre nom","Type d'œuvre","Dimensions approximatives","Décrivez votre idée ou l'espace concerné"],
 opts=["Tableau","Œuvre murale / fresque","Sol / médaillon","Piscine / fontaine","Autre"],send="Présenter mon projet à l'atelier",note="Le message s'ouvre dans WhatsApp, vous pouvez y joindre photos et plans. Ce site n'enregistre aucune donnée.",wa="Bonjour, je souhaite présenter un projet à LITHOS IMPERIAL.",
 lh="Mentions légales et confidentialité",lp=["Éditeur : Kosta Imed LITHOS, atelier LITHOS IMPERIAL, Camporosso Mare (IM), Italie. Tél. +39 351 386 6250. N° TVA / P.IVA : [à compléter]. Hébergement : GitHub Pages (GitHub, Inc., États-Unis).","Confidentialité (RGPD, règlement UE 2016/679) : ce site n'utilise ni cookies ni outil de suivi. Le message et les fichiers envoyés via le formulaire servent uniquement à répondre à votre demande ; ils transitent par des prestataires techniques (stockage de fichiers, messagerie) et ne sont conservés que le temps nécessaire à son traitement. L'hébergeur peut journaliser votre adresse IP pour la sécurité. Vos droits d'accès, de rectification et d'effacement s'exercent auprès de l'atelier ; vous pouvez saisir le Garante per la protezione dei dati personali.","Les œuvres et photographies présentées sont la propriété de l'atelier ; toute reproduction sans autorisation est interdite."],pv="Contact"),
'en':dict(t="LITHOS IMPERIAL — Mosaic artist, bespoke handcrafted stone mosaics",d="Mosaic art atelier in Camporosso Mare (Liguria, Italy): bespoke mosaic artworks, murals, floors, pools and reproductions of Roman and Carthaginian mosaics, handmade in natural stone.",
 tag="Original creations and reproductions shaped by hand in natural stone, inspired by the traditions of Carthage and Rome.",sig="The art of antique mosaic, made to measure",c1="Present my project",c2="Discover the works",
 nav=["Works","Bespoke","Reproductions","The atelier","Contact"],
 ih="A work begins with a stone.",ip="Every mosaic is assembled as a work of art. The material, the cut, the direction of the tesserae and the natural irregularities of the stone give it character. From a small collector's piece to a monumental composition, the atelier creates original works and reproductions, fitted to the size and spirit of your project.",
 wh="The works",wz="Click to examine the details",W=[("The tree of life","Medallion"),("Khamsa","Panel"),("Floor with fish","Floor"),("Pillar with knotwork","Mural work"),("Foliate border","Work in progress")],
 cats=["Panels and collector's pieces","Murals and frescoes","Floors, medallions and compositions","Pools, basins and fountains"],
 ch="Create what does not exist yet",cp="An idea, an image, an emotion or simply a material can become a mosaic artwork. The atelier adapts subject, dimensions, materials and shades to your project.",steps=["Idea","Conversation","Artistic study","Choice of materials","Handmade execution","Finished work"],
 rh="Masterpieces of the past, reinterpreted by the mosaicist's hand",rp="Reproductions of historic mosaics and reference works, faithful to their composition and detail, at the size you choose. Inspired by the mosaic traditions of Carthage and Rome. Ancient public-domain works may be reproduced freely; a work still under copyright requires permission from the rights holders.",
 gh="The hand before the machine",gp="Every tessera shapes the work. Variations in colour, texture and veining are not flaws to erase: they are the personality of the stone. Cut and set one by one, by hand.",
 ah="In the atelier",ap="Kosta Imed LITHOS, mosaic craftsman, creates bespoke mosaic artworks in Camporosso Mare (Liguria). When a project calls for it, he works with owners, architects, decorators and designers: you imagine the space, the atelier makes the mosaic.",
 ph="Present my project",pp="An idea, an image, a space? Describe it: every request is studied individually by the atelier.",fl=["Your name","Type of work","Approximate dimensions","Describe your idea or the space"],
 opts=["Panel","Mural / fresco","Floor / medallion","Pool / fountain","Other"],send="Present my project to the atelier",note="The message opens in WhatsApp, where you can attach photos and plans. This site stores no data.",wa="Hello, I would like to present a project to LITHOS IMPERIAL.",
 lh="Legal notice and privacy",lp=["Publisher: Kosta Imed LITHOS, atelier LITHOS IMPERIAL, Camporosso Mare (IM), Italy. Tel. +39 351 386 6250. VAT / P.IVA: [to be completed]. Hosting: GitHub Pages (GitHub, Inc., USA).","Privacy (GDPR, EU Regulation 2016/679): this site uses no cookies or tracking. The message and files sent through the form are used only to answer your request; they pass through technical providers (file storage, messaging) and are kept only as long as needed to handle it. The host may log your IP address for security. You may exercise your rights of access, rectification and erasure with the atelier, or contact the Italian Garante per la protezione dei dati personali.","The works and photographs shown belong to the atelier; reproduction without permission is prohibited."],pv="Contact"),
'it':dict(t="LITHOS IMPERIAL — Mosaicista d'arte, mosaici su misura in pietra naturale",d="Atelier di mosaico artistico a Camporosso Mare (Liguria): quadri, murali, pavimenti, piscine e riproduzioni di mosaici romani e cartaginesi, fatti a mano in pietra naturale.",
 tag="Creazioni originali e riproduzioni modellate a mano in pietra naturale, ispirate alle tradizioni di Cartagine e di Roma.",sig="L'arte del mosaico antico su misura",c1="Presenta il tuo progetto",c2="Scopri le opere",
 nav=["Opere","Su misura","Riproduzioni","L'atelier","Contatto"],
 ih="Un'opera comincia da una pietra.",ip="Ogni mosaico è composto come un'opera d'arte. La materia, il taglio, l'orientamento delle tessere e le irregolarità naturali della pietra ne fanno il carattere. Dal piccolo pezzo da collezione alla composizione monumentale, l'atelier realizza creazioni originali e riproduzioni, adatte alle dimensioni e allo spirito del progetto.",
 wh="Le opere",wz="Clicca per esaminare i dettagli",W=[("L'albero della vita","Medaglione"),("Khamsa","Quadro"),("Pavimento con pesci","Pavimento"),("Pilastro a intrecci","Opera murale"),("Bordo vegetale","Composizione in corso")],
 cats=["Quadri e pezzi da collezione","Opere murali e affreschi","Pavimenti, medaglioni e composizioni","Piscine, vasche e fontane"],
 ch="Creare ciò che ancora non esiste",cp="Un'idea, un'immagine, un'emozione o semplicemente una materia possono diventare un mosaico. L'atelier adatta soggetto, dimensioni, materiali e sfumature al tuo progetto.",steps=["Idea","Confronto","Studio artistico","Scelta dei materiali","Realizzazione a mano","Opera finita"],
 rh="I capolavori del passato, reinterpretati dalla mano del mosaicista",rp="Riproduzioni di mosaici storici e opere di riferimento, fedeli a composizione e dettagli, nella dimensione desiderata. Ispirate alle tradizioni musive di Cartagine e di Roma. Le opere antiche di pubblico dominio si possono riprodurre liberamente; un'opera ancora protetta dal diritto d'autore richiede l'autorizzazione degli aventi diritto.",
 gh="La mano prima della macchina",gp="Ogni tessera partecipa all'opera. Le variazioni di colore, texture e venatura non sono difetti da cancellare: sono la personalità della materia. Tagliate e posate una a una, a mano.",
 ah="Nell'atelier",ap="Kosta Imed LITHOS, artigiano mosaicista, crea opere in mosaico su misura a Camporosso Mare (Liguria). Quando il progetto lo richiede collabora con proprietari, architetti, decoratori e designer: voi immaginate lo spazio, l'atelier realizza il mosaico.",
 ph="Presenta il tuo progetto",pp="Un'idea, un'immagine, uno spazio? Descrivilo: ogni richiesta è valutata singolarmente dall'atelier.",fl=["Il tuo nome","Tipo di opera","Dimensioni approssimative","Descrivi l'idea o lo spazio"],
 opts=["Quadro","Opera murale / affresco","Pavimento / medaglione","Piscina / fontana","Altro"],send="Presenta il progetto all'atelier",note="Il messaggio si apre in WhatsApp, dove puoi allegare foto e planimetrie. Questo sito non salva alcun dato.",wa="Buongiorno, vorrei presentare un progetto a LITHOS IMPERIAL.",
 lh="Note legali e privacy",lp=["Editore: Kosta Imed LITHOS, atelier LITHOS IMPERIAL, Camporosso Mare (IM), Italia. Tel. +39 351 386 6250. P.IVA: [da completare]. Hosting: GitHub Pages (GitHub, Inc., USA).","Privacy (GDPR, Reg. UE 2016/679): il sito non usa cookie né strumenti di tracciamento. Il messaggio e i file inviati con il modulo servono solo a rispondere alla richiesta; transitano da fornitori tecnici (archiviazione file, messaggistica) e sono conservati solo per il tempo necessario. L'host può registrare l'indirizzo IP per sicurezza. Puoi esercitare i diritti di accesso, rettifica e cancellazione presso l'atelier o rivolgerti al Garante per la protezione dei dati personali.","Opere e fotografie sono di proprietà dell'atelier; ne è vietata la riproduzione senza autorizzazione."],pv="Contatto")}
CSS="""*{box-sizing:border-box;margin:0}html{scroll-behavior:smooth;scroll-padding-top:4rem}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
:root{--k:#0f0d0b;--i:#f2ede2;--t:#d8ceb8;--g:#8b857a;--b:#4b4034;--o:#c4a86a}
body{background:var(--k);color:var(--i);font:17px/1.65 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
h1,h2,h3,.brand{font-family:"Iowan Old Style","Palatino Linotype",Palatino,"Book Antiqua",Georgia,serif;font-weight:400;line-height:1.15}
a{color:inherit}:focus-visible{outline:2px solid var(--o);outline-offset:3px}
header{position:fixed;inset:0 0 auto;z-index:5;display:flex;gap:1rem;align-items:center;justify-content:space-between;padding:.8rem 5vw;background:linear-gradient(#0f0d0bd9,#0f0d0b00)}
.brand{text-decoration:none;font-size:1.15rem;letter-spacing:.14em;display:flex;align-items:center;gap:.6rem}.brand img{width:34px;height:34px}
nav{display:flex;gap:1.4rem;font-size:.9rem}nav a{text-decoration:none;opacity:.85}nav a:hover{opacity:1}.lang{font-size:.85rem;display:flex;gap:.6rem}.lang a{text-decoration:none;opacity:.6}.lang a[aria-current]{opacity:1;color:var(--o)}
@media(max-width:860px){nav{display:none}}
.hero{position:relative;min-height:100svh;display:grid;align-content:end;padding:0 5vw 12vh}.hero>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;z-index:-1}
.hero:before{content:"";position:absolute;inset:0;background:linear-gradient(#0f0d0b66,#0f0d0bf2 88%);z-index:-1}
h1{font-size:clamp(2.4rem,7vw,5.5rem);letter-spacing:.06em}.sig{font-size:1.1rem;letter-spacing:.06em;color:var(--o);margin:.6rem 0 1rem}.tag{max-width:36rem;color:var(--t)}
.btns{display:flex;flex-wrap:wrap;gap:.8rem;margin-top:1.8rem}.btn{display:inline-block;padding:.9rem 1.5rem;border:1px solid var(--o);text-decoration:none;font-size:.85rem;letter-spacing:.1em;text-transform:uppercase;background:none;color:var(--i);cursor:pointer;font-family:inherit}.btn.p{background:var(--o);color:var(--k)}.btn:hover{filter:brightness(1.12)}
section{padding:clamp(3.5rem,9vw,7rem) 5vw}.light{background:var(--i);color:var(--k)}.light .btn{color:var(--k)}
h2{font-size:clamp(1.8rem,4vw,3rem);max-width:22ch;margin-bottom:1.2rem}.wrap{max-width:46rem}.light p,.wrap p{color:inherit}.dim{color:var(--t)}
.grid{display:grid;gap:1rem;grid-template-columns:repeat(auto-fill,minmax(min(100%,16rem),1fr));margin:2rem 0}
figure{margin:0;position:relative;background:#000}figure img{display:block;width:100%;aspect-ratio:4/5;object-fit:cover;cursor:zoom-in}figcaption{padding:.6rem .2rem;font-size:.9rem;color:var(--t)}figcaption b{font-weight:400;display:block;color:var(--i);font-family:Georgia,serif;font-size:1.05rem}
.cats{list-style:none;padding:0;display:grid;gap:.4rem;margin-top:1rem;color:var(--t)}
ol{padding-left:1.2rem;display:grid;gap:.3rem;margin:1.2rem 0}.geste{display:grid;gap:1rem;grid-template-columns:repeat(auto-fit,minmax(min(100%,14rem),1fr));margin-top:2rem}.geste img{width:100%;height:100%;max-height:26rem;object-fit:cover;display:block}
form{display:grid;gap:.9rem;max-width:36rem;margin-top:1.5rem}input,select,textarea{width:100%;padding:.8rem;background:#1b1814;color:var(--i);border:1px solid var(--b);font:inherit}textarea{min-height:7rem}label{font-size:.85rem;color:var(--t);display:grid;gap:.3rem}.small{font-size:.85rem;color:var(--g)}
footer{padding:2.5rem 5vw 6rem;font-size:.85rem;color:var(--g)}footer p{max-width:60rem;margin-top:.7rem}
.fab{position:fixed;right:1rem;bottom:1rem;z-index:6;padding:.75rem 1.2rem;background:var(--k);border:1px solid var(--o);font-size:.78rem;letter-spacing:.1em;text-transform:uppercase;text-decoration:none}
dialog{border:0;background:#000e;max-width:100vw;max-height:100vh;width:100%;height:100%;padding:0}dialog::backdrop{background:#000}.lb{width:100%;height:100%;overflow:auto;display:grid;place-items:center}.lb img{max-width:100%;max-height:100vh;cursor:zoom-in;transition:transform .2s}.lb img.z{transform:scale(2.6);cursor:zoom-out}
dialog button{position:fixed;top:.8rem;right:1rem;z-index:2;background:var(--k);color:var(--i);border:1px solid var(--o);padding:.5rem .9rem;cursor:pointer}
header{background:#0f0d0bf2}.brand{white-space:nowrap;font-size:1rem;letter-spacing:.1em}
.hero{position:static;display:grid;min-height:0;padding:3.6rem 0 0;align-content:normal;background:var(--k)}.hero:before{display:none}
.ph{position:relative;height:56svh;overflow:hidden}.ph img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:40% 50%}
.tx{padding:2.2rem 5vw 3.5rem}.tx .btn:not(.p){background:#1b1814}
@media(min-width:900px){.hero{grid-template-columns:1fr 1fr;min-height:100svh}.ph{order:2;height:auto}.tx{align-self:center;padding:4rem 5vw}}
.fab{opacity:0;pointer-events:none;transition:opacity .25s}.fab.on{opacity:1;pointer-events:auto}
.kind{border:0;padding:0;display:grid;grid-template-columns:1fr 1fr;gap:.6rem}legend{color:var(--t);font-size:.85rem;margin-bottom:.5rem}
.opt{display:block;position:relative;color:var(--i)}.opt input{position:absolute;opacity:0;width:1px}.opt span{display:block;padding:1.1rem .5rem;border:1px solid var(--b);text-align:center;cursor:pointer;font-family:Georgia,serif;font-size:1.05rem}
.opt input:checked+span{border-color:var(--o);background:#1b1814;color:var(--o)}.opt input:focus-visible+span{outline:2px solid var(--o);outline-offset:3px}input[type=file]{padding:.7rem}
.alt{background:#191512;border-top:1px solid #ffffff14}#artiste p{margin-top:1rem}.tl{list-style:none;margin-top:2rem;display:grid;gap:1.1rem;border-left:1px solid var(--o);padding-left:1.2rem}.tl li{display:grid;gap:.1rem;color:var(--t)}.tl b{font-family:Georgia,serif;font-weight:400;color:var(--i);font-size:1.15rem}
.ph{display:flex;flex-direction:column;height:auto;background:#000;overflow:hidden}.car{display:flex;flex-direction:column;flex:1;min-height:0}.trk{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;height:56svh;background:#000}.trk::-webkit-scrollbar{display:none}.sl{flex:0 0 100%;scroll-snap-align:center;position:relative}.ph .sl img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}
.ctl{display:flex;align-items:center;gap:.4rem;padding:.5rem .8rem;background:var(--k);border-top:1px solid #ffffff1a}.ctl button{background:none;border:1px solid var(--b);color:var(--i);width:2.7rem;height:2.7rem;font-size:1.1rem;cursor:pointer}.ctl span{flex:1;min-width:0;font-size:.9rem;color:var(--t);padding-left:.6rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
@media(min-width:900px){.ph{height:calc(100svh - 3.6rem)}.trk{height:auto;flex:1}}
"""
JS="""var d=document,lb=d.getElementById('lb'),li=lb.querySelector('img');
d.querySelectorAll('figure img').forEach(function(i){i.onclick=function(){li.src=i.dataset.full;li.alt=i.alt;li.className='';lb.showModal()}});
li.onclick=function(e){var r=li.getBoundingClientRect();li.style.transformOrigin=(e.clientX-r.left)/r.width*100+'% '+(e.clientY-r.top)/r.height*100+'%';li.classList.toggle('z')};
lb.querySelector('button').onclick=function(){lb.close()};
d.querySelectorAll('.lang a').forEach(function(a){a.onclick=function(){try{localStorage.lang=a.hreflang}catch(e){}}});
var f=d.getElementById('pf'),st=d.getElementById('st'),NL=String.fromCharCode(10),g=function(n){return f.elements[n].value};
var ff=d.getElementById('ff');f.onsubmit=function(e){e.preventDefault();var fs=[].slice.call(ff.files),t=[f.dataset.wa,g('k')+' / '+g('t'),g('s'),g('m'),g('n'),g('c')].filter(Boolean).join(NL);
if(fs.length&&navigator.canShare&&navigator.canShare({files:fs})){navigator.share({files:fs,text:t}).then(function(){st.textContent=f.dataset.done}).catch(function(){})}
else{open('https://wa.me/WAWA?text='+encodeURIComponent(t));st.textContent=fs.length?f.dataset.att:f.dataset.done}};
var fab=d.querySelector('.fab'),vis={};if(window.IntersectionObserver){var io=new IntersectionObserver(function(es){es.forEach(function(e){vis[e.target.id]=e.isIntersecting});fab.classList.toggle('on',!vis.h&&!vis.projet)});io.observe(d.getElementById('h'));io.observe(d.getElementById('projet'))}else fab.classList.add('on')
;(function(){var t=d.getElementById('trk');if(!t)return;var n=t.children.length,i=0,pz=matchMedia('(prefers-reduced-motion:reduce)').matches,hold=0,hb,pp=d.getElementById('pp'),cp=d.getElementById('cp');
function lab(){cp.textContent=t.children[i].dataset.t+'  ('+(i+1)+'/'+n+')'}
function st(){pp.textContent=pz?'▶':'❚❚';pp.setAttribute('aria-label',pz?pp.dataset.play:pp.dataset.pause)}
function go(k){var w=k<0||k>=n;i=(k+n)%n;t.scrollTo({left:i*t.clientWidth,behavior:w?'auto':'smooth'});lab()}
t.addEventListener('scroll',function(){var j=Math.round(t.scrollLeft/t.clientWidth);if(j!==i&&j>=0&&j<n){i=j;lab()}});
function h(){hold=1;clearTimeout(hb);hb=setTimeout(function(){hold=0},6000)}
t.addEventListener('touchstart',h,{passive:true});t.addEventListener('mouseenter',function(){hold=1});t.addEventListener('mouseleave',function(){hold=0});
t.addEventListener('keydown',function(e){if(e.key==='ArrowLeft')go(i-1);if(e.key==='ArrowRight')go(i+1)});
d.getElementById('pv').onclick=function(){go(i-1)};d.getElementById('nx').onclick=function(){go(i+1)};pp.onclick=function(){pz=!pz;st()};
setInterval(function(){if(!pz&&!hold&&!d.hidden&&n>1)go(i+1)},3000);lab();st()})();
""".replace("WAWA",WA)
X={'fr': {'kl': 'Votre projet est…', 'k1': 'Création originale', 'k2': 'Reproduction', 'up': 'Photos, croquis ou vidéos de référence', 'uh': "Photos et vidéos acceptées, jusqu'à 100 Mo par fichier. Sur téléphone, vous pouvez photographier directement.", 'ct': 'Téléphone ou email', 'wait': 'Envoi en cours…', 'done': "Merci : votre projet est bien arrivé à l'atelier.", 'err': "L'envoi a échoué. Écrivez-nous sur WhatsApp au +39 351 386 6250.", 'nocloud': '(Je vous enverrai mes photos et vidéos ici, sur WhatsApp.)', 'note': "Votre message et vos fichiers sont transmis uniquement à l'atelier."}, 'en': {'kl': 'My project is…', 'k1': 'An original creation', 'k2': 'A reproduction', 'up': 'Photos, sketches or reference videos', 'uh': 'Photos and videos accepted, up to 100 MB per file. On a phone you can shoot directly.', 'ct': 'Phone or email', 'wait': 'Sending…', 'done': 'Thank you: your project has reached the atelier.', 'err': 'Sending failed. Please write to us on WhatsApp at +39 351 386 6250.', 'nocloud': '(I will send my photos and videos here, on WhatsApp.)', 'note': 'Your message and files are sent only to the atelier.'}, 'it': {'kl': 'Il mio progetto è…', 'k1': 'Una creazione originale', 'k2': 'Una riproduzione', 'up': 'Foto, schizzi o video di riferimento', 'uh': 'Foto e video accettati, fino a 100 MB per file. Da telefono puoi scattare direttamente.', 'ct': 'Telefono o email', 'wait': 'Invio in corso…', 'done': "Grazie: il tuo progetto è arrivato all'atelier.", 'err': 'Invio non riuscito. Scrivici su WhatsApp al +39 351 386 6250.', 'nocloud': '(Ti invierò foto e video qui, su WhatsApp.)', 'note': "Il messaggio e i file sono inviati solo all'atelier."}}

NEW={'fr':dict(done="WhatsApp s'ouvre : envoyez le message et joignez-y vos photos ou vidéos.",note="Le message s'ouvre dans WhatsApp, où vous pouvez joindre photos, plans et vidéos. Ce site n'enregistre aucune donnée.",
lp="Confidentialité (RGPD, règlement UE 2016/679) : ce site n'utilise ni cookies ni outil de suivi et ne collecte ni ne stocke aucune donnée. Le formulaire prépare un message WhatsApp que vous envoyez vous-même ; WhatsApp le traite ensuite selon sa propre politique. L'hébergeur (GitHub Pages) peut journaliser votre adresse IP pour la sécurité. Vos droits d'accès, de rectification et d'effacement s'exercent auprès de l'atelier ; vous pouvez saisir le Garante per la protezione dei dati personali."),
'en':dict(done="WhatsApp opens: send the message and attach your photos or videos.",note="The message opens in WhatsApp, where you can attach photos, plans and videos. This site stores no data.",
lp="Privacy (GDPR, EU Regulation 2016/679): this site uses no cookies or tracking and neither collects nor stores any data. The form prepares a WhatsApp message that you send yourself; WhatsApp then processes it under its own policy. The host (GitHub Pages) may log your IP address for security. You may exercise your rights of access, rectification and erasure with the atelier, or contact the Italian Garante per la protezione dei dati personali."),
'it':dict(done="Si apre WhatsApp: invia il messaggio e allega foto o video.",note="Il messaggio si apre in WhatsApp, dove puoi allegare foto, planimetrie e video. Questo sito non salva alcun dato.",
lp="Privacy (GDPR, Reg. UE 2016/679): il sito non usa cookie né tracciamento e non raccoglie né conserva dati. Il modulo prepara un messaggio WhatsApp che invii tu stesso; WhatsApp lo tratta poi secondo la propria informativa. L'host (GitHub Pages) può registrare l'indirizzo IP per sicurezza. Puoi esercitare i diritti di accesso, rettifica e cancellazione presso l'atelier o rivolgerti al Garante per la protezione dei dati personali.")}
for lg,v in NEW.items():
    T[lg]['lp'][1]=v.pop('lp');X[lg].update(v)

NEW2={'fr':dict(up="Photos, croquis ou vidéos de référence",note="Seul le téléphone ou l'e-mail est obligatoire. Photos et vidéos : sur téléphone, un menu de partage s'ouvre, choisissez WhatsApp puis l'atelier.",att="WhatsApp s'ouvre : envoyez le message, puis joignez vos photos et vidéos avec le trombone.",done="Envoyez le message à l'atelier via WhatsApp (+39 351 386 6250).",cpv="Œuvre précédente",cnx="Œuvre suivante",cpa="Mettre en pause",cpl="Lancer le défilement",cal="Diaporama des œuvres",an="L'artiste",ah2="L'artiste",
bio=["Depuis 1997, Kosta Imed LITHOS consacre sa vie à un seul geste : donner à la pierre la voix d'une image. Près de trente ans de pratique lui ont appris ce qu'aucune école ne transmet seule : lire la veine d'un marbre, sentir l'instant où une tesselle trouve sa place, faire naître de milliers de fragments une composition qui semble avoir toujours existé.","Son parcours suit la Méditerranée. Il exerce d'abord à Tunis, héritière de la grande tradition mosaïste de Carthage, puis, dès 2008, au Pirée, près d'Athènes, au contact d'un autre patrimoine antique. Son atelier se trouve aujourd'hui à Camporosso Mare, près d'Imperia, en Ligurie.","Ses ouvrages — tableaux, fresques, pavements, décors de bassins et de demeures — portent la même signature : une main sûre, une palette de pierres choisies une à une et le refus de la facilité. Chaque commande est traitée comme une œuvre unique, du premier croquis à la dernière tesselle."],
tl=[("1997","Tunis : début d'une pratique de près de trente ans"),("2008","Le Pirée, Athènes"),("Aujourd'hui","Camporosso Mare, Imperia (Ligurie) : l'atelier LITHOS IMPERIAL")]),
'en':dict(up="Photos, sketches or reference videos",note="Only a phone number or email is required. Photos and videos: on a phone a share menu opens, choose WhatsApp then the atelier.",att="WhatsApp opens: send the message, then attach your photos and videos with the paperclip.",done="Send the message to the atelier on WhatsApp (+39 351 386 6250).",cpv="Previous work",cnx="Next work",cpa="Pause",cpl="Start slideshow",cal="Slideshow of the works",an="The artist",ah2="The artist",
bio=["Since 1997, Kosta Imed LITHOS has devoted his life to a single gesture: giving stone the voice of an image. Nearly thirty years of practice have taught him what no school teaches alone: reading the vein of a marble, sensing the moment a tessera finds its place, and drawing from thousands of fragments a composition that seems to have always existed.","His path follows the Mediterranean. He worked first in Tunis, heir to the great mosaic tradition of Carthage, then from 2008 in Piraeus, near Athens, alongside another ancient legacy. His atelier is today in Camporosso Mare, near Imperia, in Liguria.","His works — panels, frescoes, floors, pool and villa decoration — bear one signature: a sure hand, a palette of stones chosen one by one, and a refusal of the easy way. Every commission is treated as a unique work, from the first sketch to the last tessera."],
tl=[("1997","Tunis: the start of a practice of nearly thirty years"),("2008","Piraeus, Athens"),("Today","Camporosso Mare, Imperia (Liguria): atelier LITHOS IMPERIAL")]),
'it':dict(up="Foto, schizzi o video di riferimento",note="Solo telefono o email sono obbligatori. Foto e video: da telefono si apre il menu di condivisione, scegli WhatsApp e poi l'atelier.",att="Si apre WhatsApp: invia il messaggio, poi allega foto e video con la graffetta.",done="Invia il messaggio all'atelier su WhatsApp (+39 351 386 6250).",cpv="Opera precedente",cnx="Opera successiva",cpa="Pausa",cpl="Avvia lo scorrimento",cal="Presentazione delle opere",an="L'artista",ah2="L'artista",
bio=["Dal 1997, Kosta Imed LITHOS dedica la vita a un solo gesto: dare alla pietra la voce di un'immagine. Quasi trent'anni di pratica gli hanno insegnato ciò che nessuna scuola trasmette da sola: leggere la venatura di un marmo, sentire l'istante in cui una tessera trova il suo posto, far nascere da migliaia di frammenti una composizione che sembra esistere da sempre.","Il suo percorso segue il Mediterraneo. Lavora prima a Tunisi, erede della grande tradizione musiva di Cartagine, poi dal 2008 al Pireo, presso Atene, a contatto con un altro patrimonio antico. Oggi il suo atelier si trova a Camporosso Mare, vicino a Imperia, in Liguria.","Le sue opere — quadri, affreschi, pavimenti, decori per vasche e dimore — portano la stessa firma: una mano sicura, una tavolozza di pietre scelte una a una e il rifiuto della facilità. Ogni commissione è trattata come un'opera unica, dal primo schizzo all'ultima tessera."],
tl=[("1997","Tunisi: inizio di una pratica di quasi trent'anni"),("2008","Il Pireo, Atene"),("Oggi","Camporosso Mare, Imperia (Liguria): atelier LITHOS IMPERIAL")])}
for lg,v in NEW2.items():X[lg].update(v)
ORD=['arbre','khamsa','sol','pilier','bordure']
import json
for lg,c in T.items():
    c.update(X[lg])
    os.makedirs(O+lg,exist_ok=True)
    alts=[f'{a}, {b} — LITHOS IMPERIAL' for a,b in c['W']]
    figs=''.join(f'<figure>{pic(k,t+" — LITHOS IMPERIAL")}<figcaption><b>{t}</b></figcaption></figure>' for k,t in P)
    slides=''.join(f'<div class="sl" data-t="{t}">{pic(k,t+" — LITHOS IMPERIAL",j==0,"(min-width:900px) 50vw,100vw")}</div>' for j,(k,t) in enumerate(P))
    car=f'<div class="car" role="region" aria-roledescription="carousel" aria-label="{c["cal"]}"><div class="trk" id="trk" tabindex="0">{slides}</div><div class="ctl"><button id="pv" type="button" aria-label="{c["cpv"]}">‹</button><button id="pp" type="button" data-play="{c["cpl"]}" data-pause="{c["cpa"]}">❚❚</button><button id="nx" type="button" aria-label="{c["cnx"]}">›</button><span id="cp"></span></div></div>'
    G=[k for k,t in P if any(w in t.lower() for w in ('geste','atelier','détail','detail'))][:3]
    gs=''.join(pic(k,dict(P)[k]+' — LITHOS IMPERIAL') for k in G)
    art=f'<section id="artiste" class="alt"><div class="wrap"><h2>{c["ah2"]}</h2>'+''.join(f'<p>{x}</p>' for x in c['bio'])+'<ol class="tl">'+''.join(f'<li><b>{a}</b>{b}</li>' for a,b in c['tl'])+'</ol></div></section>'
    hl=''.join(f'<link rel="alternate" hreflang="{x}" href="{SITE}{x}/">' for x in T)+f'<link rel="alternate" hreflang="x-default" href="{SITE}">'
    ld='{"@context":"https://schema.org","@type":"LocalBusiness","name":"LITHOS IMPERIAL","description":%s,"url":"%s%s/","image":"%simg/og.jpg","telephone":"%s","founder":{"@type":"Person","name":"Kosta Imed LITHOS"},"address":{"@type":"PostalAddress","addressLocality":"Camporosso Mare","addressRegion":"Imperia","addressCountry":"IT"},"knowsLanguage":["fr","en","it"]}'%(json.dumps(c['d'],ensure_ascii=False),SITE,lg,SITE,TEL)
    langs=''.join(f'<a href="../{x}/" hreflang="{x}" lang="{x}"'+(' aria-current="page"' if x==lg else '')+f'>{x.upper()}</a>' for x in T)
    n=c['nav']
    html=f'''<!doctype html><html lang="{lg}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{c['t']}</title><meta name="description" content="{c['d']}"><link rel="canonical" href="{SITE}{lg}/">{hl}<meta name="theme-color" content="#0f0d0b"><link rel="icon" href="../favicon-32.png" sizes="32x32"><link rel="apple-touch-icon" href="../apple-touch-icon.png"><meta property="og:type" content="website"><meta property="og:title" content="{c['t']}"><meta property="og:description" content="{c['d']}"><meta property="og:image" content="{SITE}img/og.jpg"><meta property="og:url" content="{SITE}{lg}/"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">{ld}</script><style>{CSS}</style></head><body>
<header><a class="brand" href="#top"><img src="../favicon-32.png" width="34" height="34" alt="">LITHOS IMPERIAL</a><nav><a href="#oeuvres">{n[0]}</a><a href="#sur-mesure">{n[1]}</a><a href="#reproductions">{n[2]}</a><a href="#artiste">{c['an']}</a><a href="#atelier">{n[3]}</a><a href="#projet">{n[4]}</a></nav><div class="lang">{langs}</div></header>
<main id="top"><section class="hero" id="h"><div class="ph">{car}</div><div class="tx"><h1>LITHOS IMPERIAL</h1><p class="sig">{c['sig']}</p><p class="tag">{c['tag']}</p><div class="btns"><a class="btn p" href="#projet">{c['c1']}</a><a class="btn" href="#oeuvres">{c['c2']}</a></div></div></section>
<section class="light"><div class="wrap"><h2>{c['ih']}</h2><p>{c['ip']}</p></div></section>
<section id="oeuvres"><h2>{c['wh']}</h2><p class="small">{c['wz']}</p><div class="grid">{figs}</div><ul class="cats">{''.join(f'<li>{x}</li>' for x in c['cats'])}</ul></section>
<section id="sur-mesure" class="light"><div class="wrap"><h2>{c['ch']}</h2><p>{c['cp']}</p><ol>{''.join(f'<li>{s}</li>' for s in c['steps'])}</ol><a class="btn" href="#projet">{c['c1']}</a></div></section>
<section id="reproductions"><div class="wrap"><h2>{c['rh']}</h2><p class="dim">{c['rp']}</p></div></section>
{art}
<section id="atelier" class="light"><div class="wrap"><h2>{c['gh']}</h2><p>{c['gp']}</p></div><div class="geste">{gs}</div><div class="wrap" style="margin-top:3rem"><h2>{c['ah']}</h2><p>{c['ap']}</p></div></section>
<section id="projet"><div class="wrap"><h2>{c['ph']}</h2><p class="dim">{c['pp']}</p>
<form id="pf" data-att="{c['att']}" data-wa="{c['wa']}" data-done="{c['done']}"><fieldset class="kind"><legend>{c['kl']}</legend><label class="opt"><input type="radio" name="k" value="{c['k1']}" checked><span>{c['k1']}</span></label><label class="opt"><input type="radio" name="k" value="{c['k2']}"><span>{c['k2']}</span></label></fieldset><label>{c['fl'][1]}<select name="t">{''.join(f'<option>{o}</option>' for o in c['opts'])}</select></label><label>{c['fl'][2]}<input name="s"></label><label>{c['fl'][3]}<textarea name="m"></textarea></label><label>{c['fl'][0]}<input name="n" autocomplete="name"></label><label>{c['ct']}<input name="c" autocomplete="tel" required></label><label>{c['up']}<input type="file" id="ff" accept="image/*,video/*" multiple></label><button class="btn p" type="submit">{c['send']}</button><p class="small" id="st" role="status">{c['note']}</p></form>
<p style="margin-top:1.5rem"><a href="https://wa.me/{WA}">WhatsApp</a> · <a href="tel:+393513866250">{TEL}</a></p><p class="small">Camporosso Mare, Imperia, Italia</p></div></section></main>
<footer><h3>{c['lh']}</h3>{''.join(f'<p>{x}</p>' for x in c['lp'])}<p>© LITHOS IMPERIAL</p></footer>
<a class="fab" href="#projet">{c['c1']}</a><dialog id="lb"><button aria-label="Close">✕</button><div class="lb"><img alt=""></div></dialog><script>{JS}</script></body></html>'''
    open(O+lg+'/index.html','w').write(html)
open(O+'index.html','w').write(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LITHOS IMPERIAL</title><meta name="description" content="{T["en"]["d"]}"><link rel="canonical" href="{SITE}">{hl}<script>try{{var l=(localStorage.lang||navigator.language||"en").slice(0,2).toLowerCase();if(!/^(fr|en|it)$/.test(l))l="en";location.replace(l+"/"+location.hash)}}catch(e){{location.replace("en/")}}</script></head><body style="background:#0f0d0b;color:#f2ede2;font-family:sans-serif;text-align:center;padding:4rem"><h1>LITHOS IMPERIAL</h1><p><a href="fr/">Français</a> · <a href="en/">English</a> · <a href="it/">Italiano</a></p></body></html>')
open(O+'robots.txt','w').write(f'User-agent: *\nAllow: /\nSitemap: {SITE}sitemap.xml\n')
open(O+'sitemap.xml','w').write('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'+''.join(f'<url><loc>{SITE}{x}/</loc>'+''.join(f'<xhtml:link rel="alternate" hreflang="{y}" href="{SITE}{y}/"/>' for y in T)+'</url>' for x in T)+'</urlset>')
open(O+'.nojekyll','w').write('')
open(O+'README.md','w').write('# LITHOS IMPERIAL\nSite statique (FR/EN/IT). Déploiement: dépôt GitHub > Settings > Pages > Branch main / root. Remplacer `https://lithosimperial.com/` (build.py: SITE) par l\'URL réelle, puis `python3 build.py`. Compléter la P.IVA dans les mentions légales.\n')

if os.path.isdir(R+'static'):
    for f in os.listdir(R+'static'):shutil.copy(R+'static/'+f,O+f)
print(len(P),'photos')
